.TH ADAN 1 "January 2026" "ADAN 0.1" "User Commands"
.SH NAME
adan \- compiler for the ADAN programming language
.SH SYNOPSIS
.B adan
.RI [ options ] " file..."
.SH DESCRIPTION
adan compiles ADAN source files into native executables.
.SH OPTIONS
.TP
.B --help
View help
.SH EXAMPLES
adan main.adn -o ./main
.SH SEE ALSO
adan(7)
.SH AUTHOR
Cappucina (Lily, Sammy, Hanna, Leo), and you the public contributers