
ASSIGNMENT = 'set', LETTERS, '=', EXPRESSION, ';' ;
VAR_DECL   = 'set', LETTERS, ':', TYPE, '=', EXPRESSION, ';' ;
CONST_DECL = 'const', LETTERS, ':', TYPE, '=', EXPRESSION, ';' ;
TYPE_DECL  = 'type', LETTERS, '=', TYPE, ';' ;
FUNCTION_METADATA_VALUE = STRING | LETTERS ;
FUNCTION_METADATA =
	'link', FUNCTION_METADATA_VALUE |
	'abi', FUNCTION_METADATA_VALUE |
	'library', FUNCTION_METADATA_VALUE |
	'visibility', FUNCTION_METADATA_VALUE ;
PARAM = LETTERS, ':', TYPE ;
PARAMS = PARAM, { ',', PARAM } ;
FUNCTION_DECL = [ 'export' ], [ 'extern' ], 'function', LETTERS, '(', [ PARAMS ], ')', ':', TYPE,
				{ FUNCTION_METADATA }, ( ';' | '{', STATEMENTS, '}' ) ;
LINK_DIRECTIVE = 'link', FUNCTION_METADATA_VALUE, ';' ;
LINK_SEARCH_DIRECTIVE = 'link_search', FUNCTION_METADATA_VALUE, ';' ;

EXPRESSION = OR_EXPR ;

OR_EXPR = AND_EXPR, { 'or', AND_EXPR } ;

AND_EXPR = NOT_EXPR, { 'and', NOT_EXPR } ;

NOT_EXPR = [ 'not' ], COMP_EXPR ;

COMP_EXPR = ARITH_EXPR, { ( '==' | '!==' | '<' | '<=' | '>' | '>=' ), ARITH_EXPR } ;

ARITH_EXPR = TERM, { ('+' | '-'), TERM } ;

TERM = FACTOR, { ('*' | '/'), FACTOR } ;

COMMAND    = LETTERS, ( '=' | '+=' | '-=' | '*=' | '/=' ), EXPRESSION, ';' ;

INCREMENT  = LETTERS, ( '++' | '--' ), ';' ;

STATEMENTS = { IF_STMT | WHILE_STMT | FOR_STMT | COMMAND | INCREMENT | VAR_DECL | CONST_DECL | TYPE_DECL | FUNCTION_DECL | LINK_DIRECTIVE | LINK_SEARCH_DIRECTIVE | BREAK_STMT | CONTINUE_STMT | EXPRESSION_STATEMENT | RETURN_STMT } ;

IF_STMT = 'if', EXPRESSION, '{', STATEMENTS, '}', [ 'else', ( IF_STMT | '{', STATEMENTS, '}' ) ] ;

WHILE_STMT = 'while', EXPRESSION, '{', STATEMENTS, '}' ;

FOR_STMT = 'for', VAR_DECL, EXPRESSION, ';', EXPRESSION, '{', STATEMENTS, '}' ;

BREAK_STMT = 'break', ';' ;

CONTINUE_STMT = 'continue', ';' ;

FACTOR = VALUE | LETTERS | '(', EXPRESSION, ')' | FUNCTION_CALL | INTERPOLATED_STRING ;

VALUE = NUMBER | STRING | 'true' | 'false' ;

TYPE = 'i8' | 'i32' | 'i64' | 'u8' | 'u32' | 'u64' | 'f32' | 'f64' | 'string' | 'bool' | 'void' | LETTERS | '{', { LETTERS, ':', TYPE, [ ',' ] }, '}', { '[]' } ;

INTERPOLATED_STRING = '"', { CHAR | '${', EXPRESSION, '}' }, '"' ;

FUNCTION_CALL = LETTERS, '(', [ ARGS ], ')' ;

ARGS = EXPRESSION, { ',', EXPRESSION } ;

RETURN_STMT = 'return', [ EXPRESSION ], ';' ;