set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_C_COMPILER "${CMAKE_CURRENT_LIST_DIR}/../scripts/zig-cc-windows-x86_64.bat")
set(CMAKE_AR "${CMAKE_CURRENT_LIST_DIR}/../scripts/zig-ar.bat")
set(CMAKE_RANLIB "${CMAKE_CURRENT_LIST_DIR}/../scripts/zig-ranlib.bat")

set(CMAKE_C_COMPILER_TARGET x86_64-windows-gnu)
set(CMAKE_C_COMPILER_FORCED TRUE)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)