set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_C_COMPILER "${CMAKE_CURRENT_LIST_DIR}/../scripts/zig-cc-macos-x86_64")
set(CMAKE_AR "${CMAKE_CURRENT_LIST_DIR}/../scripts/zig-ar")
set(CMAKE_RANLIB "${CMAKE_CURRENT_LIST_DIR}/../scripts/zig-ranlib")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
